### ISSUE TITLE
how to use use ALLOW FILTERING in compare-taxa

### ISSUE THREAD

**Issue by robertoorellanar** [MG-RAST/MG-RAST-Tools#154]
Hello, 
I am very new using MGRAST Tools and I have the following problem. I am trying to use the mg-compare-taxa tool to get the taxonomic abundance profiles of many metagenomes. 
As indicated in the script, I try the example: 

python mg-compare-taxa.py --ids "mgm4441679.3,mgm4441680.3,mgm4441681.3,mgm4441682.3" --level class --source RefSeq --format text --evalue 8

and I get the following error code:

ERROR (500): unable to build BIOM profile: an exception of type InvalidRequest occured. Arguments:
('Error from server: code=2200 [Invalid query] message="Cannot execute this query as it might involve data filtering and thus may have unpredictable performance. If you want to execute this query despite the performance unpredictability, use ALLOW FILTERING	"',)

do you guys have any idea of the meaning of this and how can be solved?

thanks a lot!

**Comment by teharrison** [comment]
There was an issue with our backend DB that was serving up the abundance profile.  It has been correct and this should now work.

**Comment by junhuili** [comment]
I still have the similar issue, I run the following example code,
`python mg-compare-functions.py --ids "mgm4441679.3,mgm4441680.3,mgm4441681.3,mgm4441682.3" --level level2 --source KO --format text --evalue 8`

and I got the error:

```
ERROR (500): unable to build BIOM profile: an exception of type SyntaxException occured. Arguments:
()
```

Any thoughts? Thank you!
